### ISSUE TITLE
Bad informations in the summary table

### ISSUE THREAD

**Issue by nicozerr** [AgenceStratis/TYPO3.be_acl#1]
Hi.

When I open Access module, there's many problems in the summary table:

All groups are displayed in the summary table. By default, it must be only owner, group and everybody.
To display one or several groups in this summary, it must be selected in the Group field above.
http://prntscr.com/bw2kll

And then, permission on each group is false. On my example, there's only one group. But in the summary, a lot of other groups have permissions.
http://prntscr.com/bw2ndx

**Comment by tomita-militaru** [comment]
Regarding the second issue, can you please give me more details? The problem is in Edit view with the select for the groups?

**Comment by nicozerr** [comment]
Sorry but I can't see Access module anymore. I get this error: http://prntscr.com/bw5rly

I cleared all caches (system, general), clear cache in the Install tool, and remove all typo3temp/ files...

**Comment by tomita-militaru** [comment]
Sorry, my bad. Try to pull now.

**Comment by nicozerr** [comment]
Hi.

on this screenshot http://prntscr.com/bx5utk, you can see that on my sysfolder 48, the summary shows permissions with content edition and page edition for GROUPE Actualités. But on this screenshot http://prntscr.com/bx5vbt, you can see there's no ACL on this page, nor on the parents pages.
In fact, permissions with page edition for GROUPE Actualités are affected for sysfolder 276, as you can see on this screenshot http://prntscr.com/bx5wky ; And permissions with content edition are affected to page 277, as you can see on this screenshot http://prntscr.com/bx5wv5.

The summary seems to show all permissions for all pages, not for current.

**Comment by nicozerr** [comment]
Another issue: in belog, I get 3 errors each time I access to Access module:
- Core: Error handler (BE): PHP Warning: Invalid argument supplied for foreach() in /home/mcolnico/public_html/typo3conf/ext/be_acl/Classes/Xclass/PermissionController.php line 108 
- Core: Error handler (BE): PHP Warning: array_map(): Argument #2 should be an array in /home/mcolnico/public_html/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1561 
- Core: Error handler (BE): PHP Warning: explode() expects parameter 2 to be string, array given in /home/mcolnico/public_html/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 1545

**Comment by tomita-militaru** [comment]
I fixed the problem with the current page, but I cannot reproduce the last issue with the log errors. Can you try with the latest master again?

**Comment by nicozerr** [comment]
All is fixed for me. Thank you !
